version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/assets/"
    schedule:
      interval: "daily"
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
