test_task:
  env:
    MIX_ENV: test
    ERLEF_COOKIE_ENCRYPTION_SALT: 41SM3UP3NgSUTzLOqCqF0r2pJBn54JuOy9+cZswJuiQi5pnCIIwJfEYO7DP3/QqR
  container:
    image: elixir:latest
  mix_cache:
    folder: deps
    fingerprint_script: cat mix.lock
    populate_script:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix deps.compile
  compile_script:
      - mix local.hex --force
      - mix local.rebar --force
      - mix compile
  test_script: mix coveralls

