test_task:
  env:
    MIX_ENV: test
    RECAPTCHA_URL: http://127.0.0.1:9998/recaptcha/api/siteverify
  container:
    image: elixir:latest
  mix_cache:
    folder: deps
    fingerprint_script: cat mix.lock
    populate_script:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix deps.compile
  compile_script:
      - mix local.hex --force
      - mix local.rebar --force
      - mix compile
  test_script: mix coveralls

