#!/bin/bash

get_repo_vars() {
    elixir -r config/to_json.exs -e ToJson.doit \
        | jq -r '
 .erlef["Elixir.Erlef.Repo"]
 | to_entries
 | map(select((.value | type) == "string"))
 | map(.key="repo_"+.key)
 | map(.key+"="+.value)
 | .[]
'
}

eval $(get_repo_vars)

test -d tmp_docker || mkdir tmp_docker

cat > tmp_docker/init-01-user-db.sh <<EOF
#!/bin/sh
set -e
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE USER
    $repo_username
    PASSWORD '$repo_password';

  CREATE DATABASE
    $repo_database
    OWNER $repo_username;
EOSQL

PGPASSWORD=$repo_password psql -v ON_ERROR_STOP=1 --user $repo_username $repo_database < /docker-entrypoint-initdb.d/backup._sql
EOF

chmod +x tmp_docker/init-01-user-db.sh
cp backup.sql tmp_docker/backup._sql

docker network create ${NETWORK:-erlef}

docker run --rm -i \
       --name $repo_hostname \
       --network ${NETWORK:-erlef} \
       --env POSTGRES_PASSWORD=postgres-pw \
       --mount type=bind,source=$(pwd)/tmp_docker/,target=/docker-entrypoint-initdb.d/ \
       --publish 5432:5432 \
       postgres:18
