#!/usr/bin/env bash

set -e

docker build --progress plain --tag localhost/erlef-otp:1.18 -f - . <<EOF
FROM docker.io/hexpm/elixir:1.18.4-erlang-27.3.4.1-alpine-3.22.1
USER root
RUN apk update && apk add npm
RUN adduser -S -u $(id -u) elixir
USER elixir
EOF

docker run --rm -it \
       --network ${NETWORK:-erlef} \
       --mount type=bind,source=$(pwd),target=/src \
       --workdir /src \
       --name website \
       --env MIX_ARCHIVES=/src/.mix \
       --env MIX_HOME=/src/.mix \
       --env HEX_HOME=/src/.hex \
       -p 4000:4000 \
       localhost/erlef-otp:1.18

#       --user $(id -u):$(id -g) \
