use Mix.Config

config :erlef, :sponsors, %{
  "adroll" => %{founding_sponsor: true, url: "https://www.adroll.com/"},
  "aeternityae" => %{founding_sponsor: true, url: "https://www.aeternity-foundation.org/"},
  "binary_noggin" => %{founding_sponsor: true, url: "https://binarynoggin.com/"},
  "cisco" => %{founding_sponsor: true, url: "https://www.cisco.com/"},
  "crevalle" => %{founding_sponsor: true, url: "https://crevalle.io/"},
  "enki" => %{founding_sponsor: true, url: "https://enki-multimedia.org/"},
  "ericsson" => %{founding_sponsor: true, url: "https://www.ericsson.com/en"},
  "esl" => %{founding_sponsor: true, url: "https://www.erlang-solutions.com/"},
  "genetec" => %{founding_sponsor: true, url: "https://www.genetec.com/"},
  "klarna" => %{founding_sponsor: true, url: "https://www.klarna.com/"},
  "otolo" => %{founding_sponsor: true, url: "https://www.otolonetworks.com/"},
  "peer" => %{founding_sponsor: true, url: "https://www.stritzinger.com/"},
  "platformatec" => %{founding_sponsor: true, url: "http://plataformatec.com.br/"},
  "simplabs" => %{founding_sponsor: true, url: "https://simplabs.com/"},
  "whatsapp" => %{founding_sponsor: true, url: "https://www.whatsapp.com/"},
  "coders51" => %{founding_sponsor: true, url: "https://www.coders51.com/"},
  "id3as" => %{founding_sponsor: true, url: "https://www.id3as.com/"},
  "sfractal" => %{founding_sponsor: true, url: "https://www.sfractal.com/"},
  "arcblock" => %{founding_sponsor: true, url: "https://www.arcblock.io/"},
  "ispirata" => %{founding_sponsor: true, url: "https://www.ispirata.com/"},
  "happi-hacking" => %{founding_sponsor: true, url: "http://happihacking.com/"},
  "dockyard" => %{founding_sponsor: false, url: "https://dockyard.com/"},
  "pepsico" => %{founding_sponsor: false, url: "https://pepsi.co/ecommerce"},
  "simplifi" => %{founding_sponsor: false, url: "https://simpli.fi/"},
  "dnsimple" => %{founding_sponsor: false, url: "https://dnsimple.com/"},
  "pharos" => %{founding_sponsor: false, url: "https://www.pharos-corp.com/"}
}
